using System;
using System.Collections;
using UnityEngine;

public class LNG
{
	private static Hashtable LanguageText = new Hashtable();

	public static void Init(string lng)
	{
		LanguageText.Clear();
		CreateLanguageHashtables(lng);
	}

	public static string Get(string sKey)
	{
		string empty = string.Empty;
		if (LanguageText.Count == 0)
		{
			CreateLanguageHashtables(PlayerPrefs.GetString("prefLang", "English"));
		}
		try
		{
			empty = (string)LanguageText[sKey];
			if (empty == null)
			{
				return "!!Key = " + sKey + " not found!!";
			}
			return empty;
		}
		catch (Exception)
		{
			return "!!Key = " + sKey + " not found!!";
		}
	}

	private static void CreateLanguageHashtables(string sLanguage)
	{
		sLanguage = sLanguage.ToLower();
		Debug.Log("Init Language: " + sLanguage);
		switch (sLanguage)
		{
		case "es":
		case "spanish":
			LanguageText.Add("ENERGY", "Energía");
			LanguageText.Add("DAMAGE", "Daño");
			LanguageText.Add("AMMO", "Muni.");
			LanguageText.Add("ARMOR", "Armadura");
			LanguageText.Add("SPEED", "Velocidad");
			LanguageText.Add("CRAFT", "Oficio");
			LanguageText.Add("REQIRED_RANK", "Rango Requerido:");
			LanguageText.Add("TOO_LESS_RES", "<color=\"#ff0000\">Sin Recursos</color>\n<color=\"#ff0000\">Suficientes</color>");
			LanguageText.Add("TOO_LOW_RANK", "<color=\"#ff0000\">Su Rango Es</color> \n<color=\"#ff0000\">Demasiado Bajo</color>");
			LanguageText.Add("LOADING", "Cargando...");
			LanguageText.Add("QUIT_GAME", "Quitar Juego");
			LanguageText.Add("MAIN_MENU", "Volver\nAl Menú");
			LanguageText.Add("SETTINGS_DISPLAY_HINTS", "Mostrar Pistas");
			LanguageText.Add("SETTINGS_VOLUME", "Volumen");
			LanguageText.Add("SETTINGS_GENDER", "Apariencia");
			LanguageText.Add("INVALID_IP", "Dirección IP inválida. Por favor introduzca una dirección IP válida. Ejemplo: 90.100.110.120");
			LanguageText.Add("NO_SERVERS_FOUND", "No se han encontrado servidores.");
			LanguageText.Add("NAME", "Nombre");
			LanguageText.Add("POPULATION", "Populación");
			LanguageText.Add("AMOUNT", "Cantidad");
			LanguageText.Add("CONDITION", "Condición");
			LanguageText.Add("VALUE", "Valor");
			LanguageText.Add("PRESS_H_FOR_HELP", "Pista: Presione H si necesita ayuda.");
			LanguageText.Add("HELP_BUILDING", "Construcción");
			LanguageText.Add("HELP_BUILDING_TEXT", "Construcción\n\nPonga una construcción como una\nvalla o una puerta en su ranura\nde mano y un holograma azul\naparecerá.\n\nSostenga derecho del ratón\npara rotar.\nPresione fuego para construir.\nRepair your buildings with\na hammer.");
			LanguageText.Add("HELP_CRAFTING", "Elaboración");
			LanguageText.Add("HELP_CRAFTING_TEXT", "Elaboración\n\nPulse el símbolo de elaboración y\nelija un objeto en la lista.\n\nSi tiene suficientes recursos\ncomo madera o metal puede conver-\ntirlos en un nuevo artículo\npresionando el botón de Elaborar.");
			LanguageText.Add("HELP_COMBAT", "Combate");
			LanguageText.Add("HELP_COMBAT_TEXT", "Combate\n\nPresione izquierdo del ratón \npara atacar con su arma \ncon sus propias manos.\n\nMarque a un jugador o NPC con\nsu botón izquierdo del ratón\ny atacará en esa dirección.\n\nPlayers with golden names are\nimmune to damage from other\nplayers (except cars) because of\ntheir 100% karma.");
			LanguageText.Add("HELP_CONTROLS", "Controles Estándar");
			LanguageText.Add("HELP_CONTROLS_TEXT", "Controles Estándar\n\nWASD: Moverse \nTAB: Inventario \nE: Interactuar \nRatón/Space: atacar \nQ: Comunicador \nM: Mapa \nC: Elaboración \nT: Chat global \nH: Ayuda \nENTER: Chat local\nF11/F12 captura de pantalla");
			LanguageText.Add("HELP_FINDINGFOOD", "Encontrar Comida");
			LanguageText.Add("HELP_FINDINGFOOD_TEXT", "Encontrar Comida\n\nEncuentre o elabore un arma y\ncace pequeños animales o recoja\nchampiñones y bayas. \n\nSi tiene tiempo suficiente,\ntambién pueden crecer sus\npropios cultivos y coséchelos.");
			LanguageText.Add("HELP_GROWINGFOOD", "Cultivar Comida");
			LanguageText.Add("HELP_GROWINGFOOD_TEXT", "Cultivar Comida\n\nDeje una patata cruda o una\nbaya en el suelo y espere\nhasta que se transforme en\nun cultivo. \n\nLos alimentos frescos crecerán\ndespués de algún tiempo.");
			LanguageText.Add("HELP_COOKINGFOOD", "Cocinar Comida");
			LanguageText.Add("HELP_COOKINGFOOD_TEXT", "Cocinar Comida\n\nElabore una hoguera y \nenciéndala con E.\n\nEche su comida cruda en\nel fuego para cocinarla.");
			LanguageText.Add("HELP_HELPTEXT", "Ayuda\n\nHaz clic en el tema\nque te interesa.");
			LanguageText.Add("TUTORIAL_MESSAGE_0", "Pista: Presiona E para recoger objetos aproximados.");
			LanguageText.Add("TUTORIAL_MESSAGE_1", "Pista: Clic derecho en un artículo comestible de tu inventario para comerlo.");
			LanguageText.Add("TUTORIAL_MESSAGE_2", "Pista: Presiona E para subir o bajar a un vehículo.");
			LanguageText.Add("TUTORIAL_MESSAGE_3", "Pista: Para cosechar recursos atacalos con el izquierdo del ratón.");
			LanguageText.Add("TUTORIAL_MESSAGE_4", "Aviso: Clic en un enemigo para enfocarlo.");
			LanguageText.Add("TUTORIAL_MESSAGE_5", "Aviso: Estas muriendo de hambre! Busca algo de comida!");
			LanguageText.Add("TUTORIAL_MESSAGE_6", "Pista: presiona Enter para chatear con otros jugadores.");
			LanguageText.Add("EVENT_2", "Vacío");
			LanguageText.Add("EVENT_3", "Prohibido!");
			LanguageText.Add("EVENT_NOWATER", "No hay agua.");
			LanguageText.Add("SERVER_RESTART_X_MINUTES", "El servidor va a reiniciar en {1} minutos. Los objetos visibles en el suelo van a desaparecer.");
			break;
		case "fr":
		case "french":
			LanguageText.Add("ENERGY", "Énergie");
			LanguageText.Add("DAMAGE", "Dommage");
			LanguageText.Add("AMMO", "Muni.");
			LanguageText.Add("ARMOR", "Armure");
			LanguageText.Add("SPEED", "Vitesse");
			LanguageText.Add("CRAFT", "Façonnage");
			LanguageText.Add("REQIRED_RANK", "Rang Requis:");
			LanguageText.Add("TOO_LESS_RES", "<color=\"#ff0000\">Pas Suffisament</color>\n<color=\"#ff0000\">De Ressources</color>");
			LanguageText.Add("TOO_LOW_RANK", "<color=\"#ff0000\">Votre Rang Est</color>\n<color=\"#ff0000\">Trop Faible</color>");
			LanguageText.Add("LOADING", "Chargement...");
			LanguageText.Add("QUIT_GAME", "Quitter Le Jeu");
			LanguageText.Add("MAIN_MENU", "Retour\nau Menu");
			LanguageText.Add("SETTINGS_DISPLAY_HINTS", "Voir Astuces");
			LanguageText.Add("SETTINGS_VOLUME", "Volume");
			LanguageText.Add("SETTINGS_GENDER", "Apparence");
			LanguageText.Add("INVALID_IP", "Adresse IP non valide. Veuillez entrer une adresse IP valide. Exemple: 90.100.110.120");
			LanguageText.Add("NO_SERVERS_FOUND", "Impossible de trouver des Serveurs.");
			LanguageText.Add("NAME", "Nom");
			LanguageText.Add("POPULATION", "Population");
			LanguageText.Add("AMOUNT", "Montant");
			LanguageText.Add("CONDITION", "Condition");
			LanguageText.Add("VALUE", "Valeur");
			LanguageText.Add("PRESS_H_FOR_HELP", "Astuce: Appuyez sur H, si vous avez besoin d'aide.");
			LanguageText.Add("HELP_BUILDING", "Bâtiment");
			LanguageText.Add("HELP_BUILDING_TEXT", "Bâtiment\n\nPlacerz un bâtiment comme une\nporte dans la fente de votre\nmain et un hologramme bleu\napparaîtra. \n\nTenez droit de la souris pour pivoter.\nAppuyez sur feu pour construire.\nRepair your buildings with\na hammer.");
			LanguageText.Add("HELP_CRAFTING", "Artisanat");
			LanguageText.Add("HELP_CRAFTING_TEXT", "Artisanat\n\nCliquez sur le symbole artisanat\net choisissez un objet dans\nla liste.\n\nSi vous avez assez de ressources\ncomme du bois ou du métal vous\npouvez les transformer en un\nnouvel élément en appuyant\nsur le bouton artisanat.");
			LanguageText.Add("HELP_COMBAT", "Combat");
			LanguageText.Add("HELP_COMBAT_TEXT", "Combat\n\nMaintenez la touche gauche de la\nsouris pour attaquer avec vos\narmes ou à mains nues.\n\nMarquez un joueur ou un PNJ\navec le bouton gauche de la\nsouris et vous attaquerez\ndans sa direction.\n\nPlayers with golden names are\nimmune to damage from other\nplayers (except cars) because of\ntheir 100% karma.");
			LanguageText.Add("HELP_CONTROLS", "Contrôles");
			LanguageText.Add("HELP_CONTROLS_TEXT", "Contrôles Standard\n\nWASD: déplacement \nTab: inventaire \nE: interagir \nSOURIS/SPACE: attaquer \nQ: communicateur \nM: carte \nC: artisanat \nT: chat global \nH: aide \nEntrée: chat local\nF11/F12 capture d'écran");
			LanguageText.Add("HELP_FINDINGFOOD", "Trouver de la Nourrit.");
			LanguageText.Add("HELP_FINDINGFOOD_TEXT", "Trouver de la Nourriture\n\nTrouvez ou façonnez une arme et\npartez à la chasse aux petits\nanimaux ou à le recherche de\nchampignons et de baies. \n\nSi vous avez le temps,\nvous pouvez aussi cultiver\nvos propres aliments.");
			LanguageText.Add("HELP_GROWINGFOOD", "Cultures Vivrières");
			LanguageText.Add("HELP_GROWINGFOOD_TEXT", "Cultures Vivrières\n\nDéposez une pomme de terre crue\nou un berry sur par terre et\nattendez jusqu'à ce qu'elle\nse cultive. \n\nDes aliments frais seront\ndéveloppés après un certain temps");
			LanguageText.Add("HELP_COOKINGFOOD", "Cuisson des Aliments");
			LanguageText.Add("HELP_COOKINGFOOD_TEXT", "Cuisson des Aliments\n\nFaçonner un foyer avec\nl'artisanat et allumez-le avec E. \n\nDéposez vos aliments crus\ndans le feu brûlant afin\nde les faire cuire.");
			LanguageText.Add("HELP_HELPTEXT", "Aide\n\nCliquez sur la rubrique\nqui que vous intéresse.");
			LanguageText.Add("TUTORIAL_MESSAGE_0", "Astuce: Appuyez sur E pour ramasser les éléments à proximité.");
			LanguageText.Add("TUTORIAL_MESSAGE_1", "Astuce: Appuyez sur le bouton droit de la souris sur un élément\nde nourriture dans votre inventaire pour le consommer.");
			LanguageText.Add("TUTORIAL_MESSAGE_2", "Astuce: Appuyez sur E pour entrer ou sortir d'un véhicule.");
			LanguageText.Add("TUTORIAL_MESSAGE_3", "Astuce: Récoltez des ressources en les attaquant avec la touche gauche de la souris.");
			LanguageText.Add("TUTORIAL_MESSAGE_4", "Astuce: Cliquez sur un ennemi pour le cibler.");
			LanguageText.Add("TUTORIAL_MESSAGE_5", "Astuce: Vous êtes affamé! Trouvez de la nourriture!");
			LanguageText.Add("TUTORIAL_MESSAGE_6", "Astuce: Appuyez sur Entrée pour discuter avec d'autres joueurs.");
			LanguageText.Add("EVENT_2", "Vide");
			LanguageText.Add("EVENT_3", "Interdit!");
			LanguageText.Add("EVENT_NOWATER", "Il n'y a pas d'eau.");
			LanguageText.Add("SERVER_RESTART_X_MINUTES", "Le serveur va être redémarré dans {1} minutes. Les éléments visibles par terre seront perdus.");
			break;
		case "it":
		case "italian":
			LanguageText.Add("ENERGY", "Energia");
			LanguageText.Add("DAMAGE", "Danno");
			LanguageText.Add("AMMO", "Muni.");
			LanguageText.Add("ARMOR", "Armatura");
			LanguageText.Add("SPEED", "Velocità");
			LanguageText.Add("CRAFT", "Crea");
			LanguageText.Add("REQIRED_RANK", "Rango Richiesto:");
			LanguageText.Add("TOO_LESS_RES", "<color=\"#ff0000\">Risorse Insuff.</color>");
			LanguageText.Add("TOO_LOW_RANK", "<color=\"#ff0000\">Il Tuo Rango</color>\n<color=\"#ff0000\">È Troppo Basso</color>");
			LanguageText.Add("LOADING", "Caricamento...");
			LanguageText.Add("QUIT_GAME", "Esci Dal Gioco");
			LanguageText.Add("MAIN_MENU", "Torna al\nMenu");
			LanguageText.Add("SETTINGS_DISPLAY_HINTS", "Mostra Suggeimenti");
			LanguageText.Add("SETTINGS_VOLUME", "Volume");
			LanguageText.Add("SETTINGS_GENDER", "Aspetto");
			LanguageText.Add("INVALID_IP", "Indirizzo IP non valido. Per favore inserisci un indirizzo IP valido. Esempio: 90.100.110.120");
			LanguageText.Add("NO_SERVERS_FOUND", "Nessun Server Trovato.");
			LanguageText.Add("NAME", "Nome");
			LanguageText.Add("POPULATION", "Popolazione");
			LanguageText.Add("AMOUNT", "Importo");
			LanguageText.Add("CONDITION", "Condizione");
			LanguageText.Add("VALUE", "Valore");
			LanguageText.Add("PRESS_H_FOR_HELP", "Suggerimento: Premi H se hai bisogno di aiuto.");
			LanguageText.Add("HELP_BUILDING", "Costruzione");
			LanguageText.Add("HELP_BUILDING_TEXT", "Costruzione\n\nPoni una costruzione come un\nrecinto o una porta nello slot\ndella tua mano e apparirà un\nologramma blu.\n\nTenere destro del mouse per ruotare.\nPremi fuoco per costruire.\nRepair your buildings with\na hammer.");
			LanguageText.Add("HELP_CRAFTING", "Creare");
			LanguageText.Add("HELP_CRAFTING_TEXT", "Creare\n\nTocca il simbolo Crea e seleziona\nun oggetto nella lista.\n\nSe hai abbastanza risorse come\nlegno o metallo potrai tras-\nformarle nel nuovo oggetto\nremendo il pulsante Crea.");
			LanguageText.Add("HELP_COMBAT", "Combatti");
			LanguageText.Add("HELP_COMBAT_TEXT", "Combatti\n\nTieni premuto sinistro del mouse\nper attaccare con la tua arma \no a mani nude.\n\nContrassegna un giocatore o\nun npc con il tasto sinistro\ndel mouse e attaccherai nella\nsua direzione.\n\nPlayers with golden names are\nimmune to damage from other\nplayers (except cars) because of\ntheir 100% karma.");
			LanguageText.Add("HELP_CONTROLS", "Controlli");
			LanguageText.Add("HELP_CONTROLS_TEXT", "Controlli Standard\n\nWASD: muovi \nTAB: inventario \nE: interagisci \nMOUSE/SPACE: attaccare \nQ: comunicatore \nM: mappa \nC: creare \nT: chat globale \nH: aiuto \nINVIO: chat locale\nF11/F12 salvare una schermata");
			LanguageText.Add("HELP_FINDINGFOOD", "Trovare Cibo");
			LanguageText.Add("HELP_FINDINGFOOD_TEXT", "Trovare Cibo\n\nTrova o crea un'arma e caccia\npiccoli animali o raccogli\nfunghi e bacche. \n\nSe hai abbastanza tempo, puoi\nanche coltivare i tuoi campi\ne fare la raccolta.");
			LanguageText.Add("HELP_GROWINGFOOD", "Coltivare Cibo");
			LanguageText.Add("HELP_GROWINGFOOD_TEXT", "Coltivare Cibo\n\nSemina una patata o una bacca\nnel terreno e attendi finchè non\nsi trasforma in un raccolto.\n\nDopo un po' di tempo\ncrescerà cibo fresco.");
			LanguageText.Add("HELP_COOKINGFOOD", "Cucinare Cibo");
			LanguageText.Add("HELP_COOKINGFOOD_TEXT", "Cucinare Cibo\n\nCrea un focolare e\naccendilo con E.\n\nAppoggia il cibo crudo sul\nfuoco acceso e cucinalo.");
			LanguageText.Add("HELP_HELPTEXT", "Aituo\n\nFai clic sull'argomento\nche ti interessa.");
			LanguageText.Add("TUTORIAL_MESSAGE_0", "Suggerimento: Premi E per raccogliere gli oggetti vicini.");
			LanguageText.Add("TUTORIAL_MESSAGE_1", "Suggerimento: Premi il Tasto Destro del Mouse su un alimento nel tuo inventario per consumarlo.");
			LanguageText.Add("TUTORIAL_MESSAGE_2", "Suggerimento: Premi E per entrare o uscire da un veicolo.");
			LanguageText.Add("TUTORIAL_MESSAGE_3", "Suggerimento: Raccogliere risorse attaccandoli con sinistro del mouse.");
			LanguageText.Add("TUTORIAL_MESSAGE_4", "Suggerimento: Clicca su un nemico per destinarli.");
			LanguageText.Add("TUTORIAL_MESSAGE_5", "Suggerimento: Stai morendo di fame! Trova del cibo!");
			LanguageText.Add("TUTORIAL_MESSAGE_6", "Suggerimento: Premi Invio per chattare con gli altri giocatori.");
			LanguageText.Add("EVENT_2", "Vuota");
			LanguageText.Add("EVENT_3", "Vietato!");
			LanguageText.Add("EVENT_NOWATER", "Non c'è acqua.");
			LanguageText.Add("SERVER_RESTART_X_MINUTES", "Il server si riavvierà fra {1} minuti. Gli oggetti visibili sul terreno andranno perduti.");
			break;
		case "tr":
		case "turkish":
			LanguageText.Add("ENERGY", "Enerji");
			LanguageText.Add("DAMAGE", "Hasar");
			LanguageText.Add("AMMO", "Cephane");
			LanguageText.Add("ARMOR", "Zırh");
			LanguageText.Add("SPEED", "Hız");
			LanguageText.Add("CRAFT", "İşle");
			LanguageText.Add("REQIRED_RANK", "Gerekli Sıralama:");
			LanguageText.Add("TOO_LESS_RES", "<color=\"#ff0000\">Yetersiz</color>\n<color=\"#ff0000\">Kaynak</color> ");
			LanguageText.Add("TOO_LOW_RANK", "<color=\"#ff0000\">Sıralaman</color>\n<color=\"#ff0000\">Çok Düşük</color>");
			LanguageText.Add("LOADING", "Yükleniyor...");
			LanguageText.Add("QUIT_GAME", "Oyundan Çık");
			LanguageText.Add("MAIN_MENU", "Ana Menüye\nGeri Dön");
			LanguageText.Add("SETTINGS_DISPLAY_HINTS", "İpuçlarını Göster");
			LanguageText.Add("SETTINGS_VOLUME", "Ses Seviyesi");
			LanguageText.Add("SETTINGS_GENDER", "Kılık");
			LanguageText.Add("INVALID_IP", "Geçersiz IP adresi. Lütfen geçerli bir IP adresi giriniz. Örneğin: 90.100.110.120");
			LanguageText.Add("NO_SERVERS_FOUND", "Sunucu Bulunamadı.");
			LanguageText.Add("NAME", "Isim");
			LanguageText.Add("POPULATION", "Nüfus");
			LanguageText.Add("AMOUNT", "Tutar");
			LanguageText.Add("CONDITION", "Durum");
			LanguageText.Add("VALUE", "Değer");
			LanguageText.Add("PRESS_H_FOR_HELP", "İpucu: Yardıma ihtiyacınız varsa H'ye basınız.");
			LanguageText.Add("HELP_BUILDING", "İnşa Etme");
			LanguageText.Add("HELP_BUILDING_TEXT", "İnşa Etme\n\nÇit veya kapı gibi yapıları\nel slotuna koyunuz. Mavi bir\nhologram belirecek. \n\nDöndürmek için farenin sağ tuşunu \nbasılı tutun.\nİnşa etmek için ateşe basınız.\nRepair your buildings with\na hammer.");
			LanguageText.Add("HELP_CRAFTING", "İşleme");
			LanguageText.Add("HELP_CRAFTING_TEXT", "İşleme\n\nTİşleme sembolüne tıklayın ve\nlisteden nesneyi seçin.\n\nEğer odun, metal gibi yeterli\nkaynaklara sahipseniz, İşleme\nbutonuna basarak onları yeni\nbir eşyaya dönüştürebilirsiniz.");
			LanguageText.Add("HELP_COMBAT", "Dövüş");
			LanguageText.Add("HELP_COMBAT_TEXT", "Dövüş\n\nSilahınızla veya ellerinizle \nsaldırmak için Sol Fare \ntuşuna basılı.\n\nFarenizin sol tuşuyla bir npc'yi\nveya oyuncu işaretleyin. O yön \ndoğrultusunda saldırıyor olacaksınız.\n\nPlayers with golden names are\nimmune to damage from other\nplayers (except cars) because of\ntheir 100% karma.");
			LanguageText.Add("HELP_CONTROLS", "Kontroller");
			LanguageText.Add("HELP_CONTROLS_TEXT", "Standard Kontroller\n\nWASD: hareket etme \nTAB: envanter \nE: etkileşim \nSOL FARE/SPACE: saldırmak için \nQ: iletişimci \nM: harita \nC: işleme \nT: küresel sohbet \nH: yardım \nENTER: yerel sohbet\nF11/F12 resim çekmek");
			LanguageText.Add("HELP_FINDINGFOOD", "Yiyecek Bulma");
			LanguageText.Add("HELP_FINDINGFOOD_TEXT", "Yiyecek Bulma\n\nBir silah bulup veya işleyip,\nufak hayvanları avlayın veya\nmantar ve meyve toplayın.\n\nVeya yeterince zamanınız varsa,\n kendi ekinlerinizi yetiştirip\nhasat edebilirsiniz.");
			LanguageText.Add("HELP_GROWINGFOOD", "Yiyecek Yetiştirmek");
			LanguageText.Add("HELP_GROWINGFOOD_TEXT", "Yiyecek Yetiştirmek\n\nBir ham patatesi veya meyveyi\nyere bırakın ve ekine dönüşene\nkadar bekleyin. \n\nTaze yiyecekler\nzamanla yetişecektir.");
			LanguageText.Add("HELP_COOKINGFOOD", "Yemek Pişirmek");
			LanguageText.Add("HELP_COOKINGFOOD_TEXT", "Yemek Pişirmek\n\nBir şömine işleyin ve\nE ile yakın. \n\nPişirmek için ham\nyiyeceğinizi ateşe bırakın.");
			LanguageText.Add("HELP_HELPTEXT", "Yardım\n\nİlgilendiğiniz konuya tıklayın.");
			LanguageText.Add("TUTORIAL_MESSAGE_0", "İpucu: Yanınızdaki eşyaları toplamak için E'ye basın.");
			LanguageText.Add("TUTORIAL_MESSAGE_1", "İpucu: Tüketmek için enventerinizdeki bir yiyecek eşyasına sağ tıkla tıklayın.");
			LanguageText.Add("TUTORIAL_MESSAGE_2", "İpucu: Bir araca binmek veya inmek için E'ye basınız.");
			LanguageText.Add("TUTORIAL_MESSAGE_3", "İpucu: Sol Fare tuşuyla saldırarak kaynakları hasat edin.");
			LanguageText.Add("TUTORIAL_MESSAGE_4", "İpucu: Hedef almak için bir düşmana tıklayın.");
			LanguageText.Add("TUTORIAL_MESSAGE_5", "İpucu: Çok acıktın! Yiyecek bul!");
			LanguageText.Add("TUTORIAL_MESSAGE_6", "İpucu: Diğer insanlarla sohbet etmek için Enter'a bas.");
			LanguageText.Add("EVENT_2", "Boş");
			LanguageText.Add("EVENT_3", "Yasak!");
			LanguageText.Add("EVENT_NOWATER", "Hiç su yok.");
			LanguageText.Add("SERVER_RESTART_X_MINUTES", "Sunucu {1} dakika içerisinde yeniden başlatılacak. Zemindeki görünür eşyalar kaybolacak.");
			break;
		case "ru":
		case "russian":
			LanguageText.Add("ENERGY", "Энергия");
			LanguageText.Add("DAMAGE", "Повреждение");
			LanguageText.Add("AMMO", "Боеприпасы");
			LanguageText.Add("ARMOR", "Броня");
			LanguageText.Add("SPEED", "Скорость");
			LanguageText.Add("CRAFT", "Ремесло");
			LanguageText.Add("REQIRED_RANK", "Необходимый рейтинг:");
			LanguageText.Add("TOO_LESS_RES", "<color=\"#ff0000\">Недостаточно</color>\n<color=\"#ff0000\">ресурсов</color> ");
			LanguageText.Add("TOO_LOW_RANK", "<color=\"#ff0000\">Ваш рэйтинг</color>\n<color=\"#ff0000\">слишком низкий</color>");
			LanguageText.Add("LOADING", "Загрузка...");
			LanguageText.Add("QUIT_GAME", "Завершить игру");
			LanguageText.Add("MAIN_MENU", "Вернуться в\nглавное меню");
			LanguageText.Add("SETTINGS_DISPLAY_HINTS", "Показать подсказки");
			LanguageText.Add("SETTINGS_VOLUME", "громкость");
			LanguageText.Add("SETTINGS_GENDER", "вид");
			LanguageText.Add("INVALID_IP", "IНеверный IP адрес. Пожалуйста, введите верный адрес IP. Пример: 90.100.110.120");
			LanguageText.Add("NO_SERVERS_FOUND", "Сервер не найден.");
			LanguageText.Add("NAME", "имя");
			LanguageText.Add("POPULATION", "жители");
			LanguageText.Add("AMOUNT", "Сумма");
			LanguageText.Add("CONDITION", "Cостояние");
			LanguageText.Add("VALUE", "Cтоимость");
			LanguageText.Add("PRESS_H_FOR_HELP", "Нажмите H, если вам нужна помощь.");
			LanguageText.Add("HELP_BUILDING", "Строительство");
			LanguageText.Add("HELP_BUILDING_TEXT", "Строительство\n\nпустите строение, например,\nзабор или дверь, в вашу\n\nДержите правую кнопку мыши, \nчтобы повернуть.\nпоявится голубая глограмма.\nRepair your buildings with\na hammer.");
			LanguageText.Add("HELP_CRAFTING", "Ремесло");
			LanguageText.Add("HELP_CRAFTING_TEXT", "Ремесло\n\nНажмите на символ ремесла и\nвыберите объект из списка.\n\nЕсли у вас достаточно ресурсов,\nдерева или металла, например,\nвы сможете превратить их в\nновый предмер, нажимая\nна кнопку Ремесло.");
			LanguageText.Add("HELP_COMBAT", "Бой");
			LanguageText.Add("HELP_COMBAT_TEXT", "Бой\n\nНажмите левой кнопкой мыши,\nчтобы атаковать при помощи\nоружия или голыми руками.\n\nОтметьте игрока или неигрового\nперсонажа левой клавишей\nклавишей мыши и вы будете\nатаковать в его направлении.\n\nPlayers with golden names are\nimmune to damage from other\nplayers (except cars) because of\ntheir 100% karma.");
			LanguageText.Add("HELP_CONTROLS", "управления");
			LanguageText.Add("HELP_CONTROLS_TEXT", "управления\n\nWASD: Инвентарь\nTAB: инвентарь \nE: взаимодействие \nМышь/SPACE: атака\nQ: коммуникатор \nM: карта \nC: ремесло \nT: глобальный чат \nH: помощь \nВВОД: локальный чат\nF11/F12 сделать скриншот");
			LanguageText.Add("HELP_FINDINGFOOD", "Поиск Пищи");
			LanguageText.Add("HELP_FINDINGFOOD_TEXT", "Поиск Пищи\n\nНайдите или сделайте оружие\nи охотьтесь на небольших\nживотных или собирайте грибы\nи ягоды.\n\nЕсли у вас достаточно времени,\nвы можете также выращивать свой\nсобственный урожай и собрать его.");
			LanguageText.Add("HELP_GROWINGFOOD", "Выращивание");
			LanguageText.Add("HELP_GROWINGFOOD_TEXT", "Выращивание Пищи\n\nБросьте один сырой помидор\nили одну ягоду в землю и\nждите, пока они \nтрансформируются в урожай. \n\nСвежая пищи вырастет\nчерез некоторое время.");
			LanguageText.Add("HELP_COOKINGFOOD", "Приготовление");
			LanguageText.Add("HELP_COOKINGFOOD_TEXT", "Приготовление Пищи\n\nПостройте камин и\nразожгите его (E).\n\nБросайте в огонь сырую пищу,\nчтобы приготовить ее.");
			LanguageText.Add("HELP_HELPTEXT", "Помошь\n\nНажмите на тему, \nкоторая вам интересна.");
			LanguageText.Add("TUTORIAL_MESSAGE_0", "намек: Нажмите E, чтобы поднять лежащие рядом предметы.");
			LanguageText.Add("TUTORIAL_MESSAGE_1", "намек: Нажмите правой клавишей мыши на позицию Пища в вашем инвентаре, чтобы питаться.");
			LanguageText.Add("TUTORIAL_MESSAGE_2", "намек: Нажмите E, чтобы войти в транспорт или выйти из него.");
			LanguageText.Add("TUTORIAL_MESSAGE_3", "намек: Собирайте ресурсы, используя левую кнопку мыши.");
			LanguageText.Add("TUTORIAL_MESSAGE_4", "намек: Нажмите на врага, чтобы прицелиться в него.");
			LanguageText.Add("TUTORIAL_MESSAGE_5", "намек: Подсказка: Вы голодаете! Найдите немного еды!");
			LanguageText.Add("TUTORIAL_MESSAGE_6", "намек: Подсказка: Нажмите Ввод, чтобы войди в чат для общения с другими игроками.");
			LanguageText.Add("EVENT_2", "Пустой");
			LanguageText.Add("EVENT_3", "запрещено!");
			LanguageText.Add("EVENT_NOWATER", "Там нет воды.");
			LanguageText.Add("SERVER_RESTART_X_MINUTES", "Сервер будет перезагружен через {1} минут. Видимые позиции на площадке будут потеряны.");
			break;
		case "pl":
		case "polish":
			LanguageText.Add("ENERGY", "Energia");
			LanguageText.Add("DAMAGE", "Uszkodzenia");
			LanguageText.Add("AMMO", "Amunicja");
			LanguageText.Add("ARMOR", "Zbroja");
			LanguageText.Add("SPEED", "Prędkość");
			LanguageText.Add("CRAFT", "Zbuduj");
			LanguageText.Add("REQIRED_RANK", "Wymagana Ranga:");
			LanguageText.Add("TOO_LESS_RES", "<color=\"#ff0000\"> Za Mało</color>\n <color=\"#ff0000\">Zasobów</color>");
			LanguageText.Add("TOO_LOW_RANK", "<color=\"#ff0000\">Ranga Jest</color>\n<color=\"#ff0000\">Zbyt Niska</color>");
			LanguageText.Add("LOADING", "Ładowanie...");
			LanguageText.Add("QUIT_GAME", "Zakończ Grę");
			LanguageText.Add("MAIN_MENU", "Powrót do\nMenu");
			LanguageText.Add("SETTINGS_DISPLAY_HINTS", "Pokaż Wskazówki");
			LanguageText.Add("SETTINGS_VOLUME", "Głośność");
			LanguageText.Add("SETTINGS_GENDER", "Wygląd");
			LanguageText.Add("INVALID_IP", "Nieprawidłowy adres IP. Proszę podać poprawny adres IP. Przykład: 90.100.110.120");
			LanguageText.Add("NO_SERVERS_FOUND", "Serwery Nie Znalezione.");
			LanguageText.Add("NAME", "Nazwa");
			LanguageText.Add("POPULATION", "Populacja");
			LanguageText.Add("AMOUNT", "Kwotę");
			LanguageText.Add("CONDITION", "Stan");
			LanguageText.Add("VALUE", "Wartość");
			LanguageText.Add("PRESS_H_FOR_HELP", "Wskazówka: Naciśnij przycisk H, jeśli potrzebujesz pomocy.");
			LanguageText.Add("HELP_BUILDING", "Budynek");
			LanguageText.Add("HELP_BUILDING_TEXT", "Budynek\n\nPostaw element budynku np:\nogrodzenie lub drzwi ze\nswojej kolekcji, a pojawi\nsię niebieski hologram.\n\nNaciśnij right mouse, aby obrócić.\nNaciśnij ogień, aby budować.\nRepair your buildings with\na hammer.");
			LanguageText.Add("HELP_CRAFTING", "Tworzenie");
			LanguageText.Add("HELP_CRAFTING_TEXT", "Tworzenie\n\nDotknij symbol tworzenia i\nwybierz obiekt z listy.\n\nJeśli masz wystarczająco dużo\nzasobów, takich jak drewno,\nmetal, możesz przekształcić je\nw nowy przedmiot poprzez\nnaciśnięcie przycisku zbuduj.");
			LanguageText.Add("HELP_COMBAT", "Walka");
			LanguageText.Add("HELP_COMBAT_TEXT", "Walka\n\nTrzymaj lewym Przyciskiem Myszy, aby\nzaatakować przy użyciu broni\nlub gołymi rękoma.\n\nOznacz gracza lub NPC lewym\nprzyciskiem myszy, a będziesz\nkować w jego kierunku.\n\nPlayers with golden names are\nimmune to damage from other\nplayers (except cars) because of\ntheir 100% karma.");
			LanguageText.Add("HELP_CONTROLS", "Stand. Kontrolery");
			LanguageText.Add("HELP_CONTROLS_TEXT", "Standardowe Kontrolery\n\nWASD: ruch \nTAB: inwentaryzacja \nE: interakcje \nMyszy/SPACE: przytrzymaj, aby zaatakować\nQ: komunikator \nM: mapa \nC: tworzenie \nT: globalny czat\nH: pomoc \nENTER: lokalny czat\nF11/F12 zrobić zrzut ekranu");
			LanguageText.Add("HELP_FINDINGFOOD", "Znalezienie Jedzenia");
			LanguageText.Add("HELP_FINDINGFOOD_TEXT", "Znalezienie Jedzenia\n\nZnajdź lub stwórz broń i\npolują na małe zwierzęta\nlub zbieraj grzyby i jagody.\n\nJeśli masz wystarczająco dużo\nczasu, możesz również hodować\nłasne uprawy i zbierać je.");
			LanguageText.Add("HELP_GROWINGFOOD", "Hodowanie Żywności");
			LanguageText.Add("HELP_GROWINGFOOD_TEXT", "Hodowanie Żywności\n\nUpuść jednego surowego ziemniaka\nlub jedną jagodę na ziemię\ni czekaj, aż zamienią się\nw uprawę. \n\nŚwieże jedzenie zajmie trochę\nczasu, aby się rozwinąć.");
			LanguageText.Add("HELP_COOKINGFOOD", "Gotowanie Jedzenia");
			LanguageText.Add("HELP_COOKINGFOOD_TEXT", "Gotowanie Jedzenia\n\nStwórz kominek i uruchom\ngo E. \n\nWrzuć swoją surową żywność\ndo ognia, aby ją ugotować.");
			LanguageText.Add("HELP_HELPTEXT", "Pomoc\n\nKliknij na temat, którym\njesteś zainteresowany.");
			LanguageText.Add("TUTORIAL_MESSAGE_0", "Wskazówka: Naciśnij E, aby podnieść przedmioty w pobliżu.");
			LanguageText.Add("TUTORIAL_MESSAGE_1", "Wskazówka: Naciśnij Prawy Przycisk Myszy na elemencie żywności w ekwipunku, by go spożyć.");
			LanguageText.Add("TUTORIAL_MESSAGE_2", "Wskazówka: Naciśnij E, aby wejść lub wyjść z pojazdu.");
			LanguageText.Add("TUTORIAL_MESSAGE_3", "Wskazówka: Zbieraj plony, atakując je lewym Przyciskiem Myszy.");
			LanguageText.Add("TUTORIAL_MESSAGE_4", "Wskazówka: Kliknij na wroga, aby go namierzyć.");
			LanguageText.Add("TUTORIAL_MESSAGE_5", "Wskazówka: Jesteś bardzo głodny! Znajdź coś do jedzenia!");
			LanguageText.Add("TUTORIAL_MESSAGE_6", "Wskazówka: Naciśnij Enter, aby rozmawiać z innymi graczami.");
			LanguageText.Add("EVENT_2", "Pusty");
			LanguageText.Add("EVENT_3", "Zakazany!");
			LanguageText.Add("EVENT_NOWATER", "Nie ma wody.");
			LanguageText.Add("SERVER_RESTART_X_MINUTES", "Serwer zostanie ponownie uruchomiony w ciągu {1} minut. \nWszystkie Widoczne elementy na ziemi zostaną utracone.");
			break;
		case "pt":
		case "portuguese-brazil":
		case "portuguese":
			LanguageText.Add("ENERGY", "Energia");
			LanguageText.Add("DAMAGE", "Dano");
			LanguageText.Add("AMMO", "Munição");
			LanguageText.Add("ARMOR", "Armadura");
			LanguageText.Add("SPEED", "Velocidade");
			LanguageText.Add("CRAFT", "Habilidade");
			LanguageText.Add("REQIRED_RANK", "Nível Necessário:");
			LanguageText.Add("TOO_LESS_RES", "<color=\"#ff0000\">Sem Minerais</color>\n <color=\"#ff0000\">O Suficiente</color>");
			LanguageText.Add("TOO_LOW_RANK", "<color=\"#ff0000\">Seu Nível é</color>\n<color=\"#ff0000\">Muito Baixo</color>");
			LanguageText.Add("LOADING", "Carregando...");
			LanguageText.Add("QUIT_GAME", "Sair do Jogo");
			LanguageText.Add("MAIN_MENU", "Voltar ao\nMenu Principal");
			LanguageText.Add("SETTINGS_DISPLAY_HINTS", "Mostrar Dicas");
			LanguageText.Add("SETTINGS_VOLUME", "Volume");
			LanguageText.Add("SETTINGS_GENDER", "Aparência");
			LanguageText.Add("INVALID_IP", "Endereço de IP inválido. Por favor digite um endereço de IP válido. Exemplo: 90.100.110.120");
			LanguageText.Add("NO_SERVERS_FOUND", "Nenhum servidor encontrado.");
			LanguageText.Add("NAME", "Nome");
			LanguageText.Add("POPULATION", "População");
			LanguageText.Add("AMOUNT", "Quantidade");
			LanguageText.Add("CONDITION", "Condição");
			LanguageText.Add("VALUE", "Valor");
			LanguageText.Add("PRESS_H_FOR_HELP", "Dica: Pressione H se você precisar de ajuda.");
			LanguageText.Add("HELP_BUILDING", "Construindo");
			LanguageText.Add("HELP_BUILDING_TEXT", "Construindo\n\nPonha uma construção como uma\ncerca ou uma porta no seu\nsuporte de mão e um holograma\nazul irá aparecer.\n\nPressione botão direito do mouse\npara rodar. Pressione botão\nesquerdo para construir.\n\nRepair your buildings with\na hammer.");
			LanguageText.Add("HELP_CRAFTING", "Funileiro");
			LanguageText.Add("HELP_CRAFTING_TEXT", "Funileiro\n\nPressione o símbolo de construção\ne escolha o objeto na lista.\n\nSe você tiver recursos suficientes\ncomo madeira ou metal, você pode\ntransformá-los em um novo item\nao pressionar o Botão Construir.");
			LanguageText.Add("HELP_COMBAT", "Combate");
			LanguageText.Add("HELP_COMBAT_TEXT", "Combate\n\nSegure o botão esquerdo do mouse\npara atacar com a sua arma ou com\nas mãos limpas.\n\nMarque um jogador ou um NPC com\num clique no botão esquerdo e você\nvai atacar em sua direção.\n\nJogadores com nomes dourados\nsão imunes a dano causado por\noutros players pois esses tem\n100% Karma.");
			LanguageText.Add("HELP_CONTROLS", "Controles Padrão");
			LanguageText.Add("HELP_CONTROLS_TEXT", "Controles Padrão\n\nWASD: movimentam o jogador\nTAB: inventário \nE: interagir\nMOUSE/ESPAÇO: atacar\nQ: comunicador \nM: mapa \nC: funileiro \nT: chat global\nH: ajuda \nENTER: chat local\nF11/F12 para tirar um print da tela");
			LanguageText.Add("HELP_FINDINGFOOD", "Encontrar Comida");
			LanguageText.Add("HELP_FINDINGFOOD_TEXT", "Encontrar Comida\n\nEncontre ou construa uma\narma e cace pequenos animais\nou encontre cogumelos e bagos.\n\nSe você tiver tempo suficiente,\nvocê também pode aumentar as\nsuas plantações e colhê-las.");
			LanguageText.Add("HELP_GROWINGFOOD", "Cultivo de Alim.");
			LanguageText.Add("HELP_GROWINGFOOD_TEXT", "Cultivo de Alimentos\n\nSolte uma batata crua ou\num bago no chão e espere\naté que ele se transforme\nem uma colheita. \n\nComida fresca irá crescer\napós algum tempo..");
			LanguageText.Add("HELP_COOKINGFOOD", "Cozinhe os Alim.");
			LanguageText.Add("HELP_COOKINGFOOD_TEXT", "Cozinhe os Alimentos\n\nConstrua uma lareira e\nacenda-a com E. \n\nBotar a sua comida crua\nno fogo para cozinhá-la.");
			LanguageText.Add("HELP_HELPTEXT", "Ajuda\n\nClique no tópico que\nvocê está interessado.");
			LanguageText.Add("TUTORIAL_MESSAGE_0", "Dica: Pressione E para pegar itens próximos.");
			LanguageText.Add("TUTORIAL_MESSAGE_1", "Dica: Pressione o botão direito do mouse em um alimento do seu inventário para consumi-lo.");
			LanguageText.Add("TUTORIAL_MESSAGE_2", "Dica: Pressione E para entrar ou deixar um veículo.");
			LanguageText.Add("TUTORIAL_MESSAGE_3", "Dica: Colha recursos atacando-os com a esquerdo do mouse.");
			LanguageText.Add("TUTORIAL_MESSAGE_4", "Dica: Clique em um inimigo para mirar nele.");
			LanguageText.Add("TUTORIAL_MESSAGE_5", "Dica: Você está faminto! Encontre alguma comida!");
			LanguageText.Add("TUTORIAL_MESSAGE_6", "Dica: Pressione Enter para conversar com outros jogadores.");
			LanguageText.Add("EVENT_2", "Vazio");
			LanguageText.Add("EVENT_3", "Proibido!");
			LanguageText.Add("EVENT_NOWATER", "Não há água.");
			LanguageText.Add("SERVER_RESTART_X_MINUTES", "O servidor irá reiniciar em {1} minutos. Itens visíveis no chão serão perdidos.");
			break;
		case "de":
		case "german":
			LanguageText.Add("ENERGY", "Energie");
			LanguageText.Add("DAMAGE", "Schaden");
			LanguageText.Add("AMMO", "Muni.");
			LanguageText.Add("ARMOR", "Rüstung");
			LanguageText.Add("SPEED", "Geschw.");
			LanguageText.Add("CRAFT", "Basteln");
			LanguageText.Add("REQIRED_RANK", "Benötigter Rank:");
			LanguageText.Add("TOO_LESS_RES", "<color=\"#ff0000\">Nicht Genug</color>\n<color=\"#ff0000\">Ressourcen</color> ");
			LanguageText.Add("TOO_LOW_RANK", "<color=\"#ff0000\">Dein Rank</color>\n<color=\"#ff0000\">Ist Zu Gering</color> ");
			LanguageText.Add("LOADING", "Lade ...");
			LanguageText.Add("QUIT_GAME", "Spiel Beenden");
			LanguageText.Add("MAIN_MENU", "Zurück\nzum Menu");
			LanguageText.Add("SETTINGS_DISPLAY_HINTS", "Tipps Anzeigen");
			LanguageText.Add("SETTINGS_VOLUME", "Lautstärke");
			LanguageText.Add("SETTINGS_GENDER", "Erscheinung");
			LanguageText.Add("INVALID_IP", "Ungültige IP. Bitte gültige IP Adresse angeben. Beispiel: 90.100.110.120");
			LanguageText.Add("NO_SERVERS_FOUND", "Keine Server gefunden.");
			LanguageText.Add("NAME", "Name");
			LanguageText.Add("POPULATION", "Population");
			LanguageText.Add("AMOUNT", "Menge");
			LanguageText.Add("CONDITION", "Zustand");
			LanguageText.Add("VALUE", "Wert");
			LanguageText.Add("PRESS_H_FOR_HELP", "Tipp: Drücke H, wenn Du Hilfe brauchst.");
			LanguageText.Add("HELP_BUILDING", "Bauen");
			LanguageText.Add("HELP_BUILDING_TEXT", "Bauen\n\nLege ein Gebäude, wie z.B. \neinen Zaun oder eine Tür in \nDeinen Hand-Slot und ein \nblaues Hologramm erscheint.\n\nHalte rechte Maus um zu rotieren.\nDrücke Feuer um zu bauen.\nRepariere Deine Gebäude mit\neinem Hammer.");
			LanguageText.Add("HELP_CRAFTING", "Basteln");
			LanguageText.Add("HELP_CRAFTING_TEXT", "Basteln\n\nÖffne die Crafting-Seite und\nwähle eine Objekt in der Liste aus. \n\nWenn Du genug Resourcen wie \nHolz oder Metall hast, \nkannst Du diese in einen \nneuen Gegenstand umwandeln.");
			LanguageText.Add("HELP_COMBAT", "Kampf");
			LanguageText.Add("HELP_COMBAT_TEXT", "Kampf\n\nKlicke mit der Maus um \nmit Deiner Waffe oder Deinen \n\nFäusten zu attackieren. \nMarkiere einen Spieler oder NPC mit\nDeiner linken Maustaste and Du \nattackierst in seine Richtung.\n\nPlayers with golden names are\nimmune to damage from other\nplayers (except cars) because of\ntheir 100% karma.");
			LanguageText.Add("HELP_CONTROLS", "Standard Tasten");
			LanguageText.Add("HELP_CONTROLS_TEXT", "Standard Tasten\n\nWASD: Bewegen \nTAB: Inventar \nE: Interaktion \nLinke Maus/Space: Attackieren \nQ: Tablet \nM: Landkarte \nC: Basteln \nT: Globaler Chat \nH: Hilfe \nENTER: Lokaler Chat\nF11/F12 Screenshot");
			LanguageText.Add("HELP_FINDINGFOOD", "Nahrung Finden");
			LanguageText.Add("HELP_FINDINGFOOD_TEXT", "Nahrung Finden\n\nFinde oder Bastle eine \nWaffe und jage kleine Tiere \noder sammle Pilze oder Beeren.\n\nWenn Du genug Zeit hast,\nkannst Du auch Nahrung\nanbauen und ernten.");
			LanguageText.Add("HELP_GROWINGFOOD", "Nahrung Anbauen");
			LanguageText.Add("HELP_GROWINGFOOD_TEXT", "Nahrung Anbauen\n\nWerfe eine rohe Kartoffel \noder eine Beere auf den Boden \nund warte bis sie sich\nin eine Pflanze verwandelt.  \n\nNach einiger Zeit wird \nfrische Nahrung wachsen.");
			LanguageText.Add("HELP_COOKINGFOOD", "Nahrung Kochen");
			LanguageText.Add("HELP_COOKINGFOOD_TEXT", "Nahrung Kochen\n\nBastle ein Lagerfeuer und \nentzünde es mit E. \n\nWirf Dein rohes Essen in das \nbrennende Feuer um es zu kochen.");
			LanguageText.Add("HELP_HELPTEXT", "Hilfe\n\nKlicke auf das Thema, \ndas Dich interessiert.");
			LanguageText.Add("TUTORIAL_MESSAGE_0", "Tipp: Drücke E um nahe Gegenstände aufzuheben.");
			LanguageText.Add("TUTORIAL_MESSAGE_1", "Tipp: Drücke rechte Maustaste über einem Nahrungitem im Inventar um es zu konsumieren.");
			LanguageText.Add("TUTORIAL_MESSAGE_2", "Tipp: Drücke E um ein-/auszusteigen.");
			LanguageText.Add("TUTORIAL_MESSAGE_3", "Tipp: Ernte Resourcen indem du sie mit mit Linker Maus attackierst.");
			LanguageText.Add("TUTORIAL_MESSAGE_4", "Tipp: Klicke auf einen Gegner um ihn zu attackieren.");
			LanguageText.Add("TUTORIAL_MESSAGE_5", "Tipp: Du verhungerst! Du brauchst Nahrung!");
			LanguageText.Add("TUTORIAL_MESSAGE_6", "Tipp: Drücke Enter um mit anderen Spielern zu reden.");
			LanguageText.Add("EVENT_2", "Leer");
			LanguageText.Add("EVENT_3", "Verboten!");
			LanguageText.Add("EVENT_NOWATER", "Hier ist kein Wasser.");
			LanguageText.Add("SERVER_RESTART_X_MINUTES", "Der Server startet in {1} Minuten neu. Sichtbare Gegenstände auf dem Boden werden gelöscht.");
			break;
		default:
			LanguageText.Add("ENERGY", "Energy");
			LanguageText.Add("DAMAGE", "Damage");
			LanguageText.Add("AMMO", "Ammo");
			LanguageText.Add("ARMOR", "Armor");
			LanguageText.Add("SPEED", "Speed");
			LanguageText.Add("CRAFT", "Craft");
			LanguageText.Add("REQIRED_RANK", "Required Rank:");
			LanguageText.Add("TOO_LESS_RES", "<color=\"#ff0000\">Not Enough</color>\n <color=\"#ff0000\">Resources</color>");
			LanguageText.Add("TOO_LOW_RANK", "<color=\"#ff0000\">Your Rank</color>\n<color=\"#ff0000\">Is Too Low</color>");
			LanguageText.Add("LOADING", "Loading...");
			LanguageText.Add("QUIT_GAME", "Quit Game");
			LanguageText.Add("MAIN_MENU", "Back to \nMain Menu");
			LanguageText.Add("SETTINGS_DISPLAY_HINTS", "Show Hints");
			LanguageText.Add("SETTINGS_VOLUME", "Volume");
			LanguageText.Add("SETTINGS_GENDER", "Appearance");
			LanguageText.Add("INVALID_IP", "Invalid IP address. Please enter a valid IP address. Example: 90.100.110.120");
			LanguageText.Add("NO_SERVERS_FOUND", "No Servers Found.");
			LanguageText.Add("NAME", "Name");
			LanguageText.Add("POPULATION", "Population");
			LanguageText.Add("AMOUNT", "Amount");
			LanguageText.Add("CONDITION", "Condition");
			LanguageText.Add("VALUE", "Value");
			LanguageText.Add("PRESS_H_FOR_HELP", "Hint: Press H if you need help.");
			LanguageText.Add("HELP_BUILDING", "Building");
			LanguageText.Add("HELP_BUILDING_TEXT", "Building\n\nPut a building like a fence \nor a door in your hand slot \nand a blue hologram will \nappear. \n\nHold right mouse to rotate. \nPress fire to build.\nRepair your buildings with\na hammer.");
			LanguageText.Add("HELP_CRAFTING", "Crafting");
			LanguageText.Add("HELP_CRAFTING_TEXT", "Crafting\n\nTap the crafting symbol and\nchoose an object in the list. \n\nIf you have enough resources \nlike wood or metal you can \nturn them into the new item \nby hitting the Craft button.");
			LanguageText.Add("HELP_COMBAT", "Combat");
			LanguageText.Add("HELP_COMBAT_TEXT", "Combat\n\nClick to attack with your \nweapon or your bare hands. \n\nMark a player or npc with \nyour left mouse button and \nyou will attack towards its \ndirection.\n\nPlayers with golden names are\nimmune to damage from other\nplayers (except cars) because of\ntheir 100% karma.");
			LanguageText.Add("HELP_CONTROLS", "Controls");
			LanguageText.Add("HELP_CONTROLS_TEXT", "Standard Controls\n\nWASD: move \nTAB: inventory \nE: interact \nLeft Mouse/Space: attack \nQ: communicator \nM: map \nC: crafting \nT: global chat \nH: help \nENTER: local chat\nF11/F12 to take a screenshot");
			LanguageText.Add("HELP_FINDINGFOOD", "Finding Food");
			LanguageText.Add("HELP_FINDINGFOOD_TEXT", "Finding Food\n\nFind or craft a weapon \nand hunt small animals or \ncollect mushrooms and \nberries. \n\nIf you have enough time, \nyou can also grow your own \ncrops and harvest them.");
			LanguageText.Add("HELP_GROWINGFOOD", "Growing Food");
			LanguageText.Add("HELP_GROWINGFOOD_TEXT", "Growing Food\n\nDrop one raw potato or one \nberry on the ground and \nwait till it transforms \ninto a crop. \n\nFresh food will grow \nafter some time.");
			LanguageText.Add("HELP_COOKINGFOOD", "Cooking Food");
			LanguageText.Add("HELP_COOKINGFOOD_TEXT", "Cooking Food\n\nCraft a fireplace and ignite \nit with E. \n\nDrop your raw food into \nthe burning fire to cook it.");
			LanguageText.Add("HELP_HELPTEXT", "Help\n\nClick on the topic you \nare interested in.");
			LanguageText.Add("TUTORIAL_MESSAGE_0", "Hint: Press E to pickup nearby items.");
			LanguageText.Add("TUTORIAL_MESSAGE_1", "Hint: Press Right Mouse on a food item in your inventory to consume it.");
			LanguageText.Add("TUTORIAL_MESSAGE_2", "Hint: Press E to enter or leave a vehicle.");
			LanguageText.Add("TUTORIAL_MESSAGE_3", "Hint: Harvest resources by attacking them with Left Mouse or Space.");
			LanguageText.Add("TUTORIAL_MESSAGE_4", "Hint: Click on an enemy to attack it.");
			LanguageText.Add("TUTORIAL_MESSAGE_5", "Hint: You are starving! Find some food!");
			LanguageText.Add("TUTORIAL_MESSAGE_6", "Hint: Press Enter to chat with other players.");
			LanguageText.Add("EVENT_2", "Empty");
			LanguageText.Add("EVENT_3", "Forbidden!");
			LanguageText.Add("EVENT_NOWATER", "There's No Water");
			LanguageText.Add("CANT_LOGOUT_DURING_BATTLE", "You can't log out during combat. Please wait %1 seconds.");
			LanguageText.Add("SERVER_RESTART_X_MINUTES", "The server will restart in {1} minutes. Visible items on the ground will be lost.");
				//broadcast
				LanguageText.Add("BROADCAST_1", "Thankyou for playing the ICE-Mod Test Server!!!\nMade by: Donaut, Charlie & Va1idUser!");
				LanguageText.Add("BROADCAST_2", "Check The Immune Steam Disscussions for info and updates!");
				//welcome
				LanguageText.Add("WELCOME_PLAYER", "Welcome {p_name} to the\nI.C.E-Mod Public Test Server.");
				LanguageText.Add("WELCOME_LEAVE", "{p_name} Left The Server.");
				LanguageText.Add("WELCOME_LEAVE2", "{p_name} Left The Server REEEE.");
				//GENERAL
				LanguageText.Add("CMD_ONLINE_PLAYERS", "Current Players Online: {p_online}.");
				LanguageText.Add("CMD_PLAYERoID", "Player O-ID is: {o_id} .");
				LanguageText.Add("CMD_PLAYERID", "Player O-ID is: {p_id} .");
				//Teleport-Player
				LanguageText.Add("TO_POS", "Teleported to [dest]!");
				LanguageText.Add("CMD_TPPLAYER", "Player {pr_name} wants to TP to you.");
				LanguageText.Add("CMD_TPACCEPTED", "TP Accepted {pr_name} will arrive soon!");
				LanguageText.Add("CMD_TPDENY", "You denied {pr_name}'s TP request.");
				LanguageText.Add("CMD_TPDENY_RESPONCE", "Your TP was denied by {p_name}.");
				LanguageText.Add("CMD_TPACCEPTED_RESPONCE", "TP Accepted by {p_name} you will arrive soon!");
				//Teleport-Building
				LanguageText.Add("CMD_TP_BUILDING", "Teleporting to {structure}!");
				//Cmd-Returns
				LanguageText.Add("CMD_PID", "ID: {cp_id} ");
				LanguageText.Add("CMD_RETURN_HP", "Added [a_hp]HP.");
				LanguageText.Add("CMD_RETURN_ENERGY", "Added [a_energy] Energy.");
				LanguageText.Add("CMD_RETURN_KARMA", "Added [a_karma] Karma.");
				LanguageText.Add("CMD_RETURN_XP", "Added [a_xp] XP.");
				//Cmd-Returns-Usage
				LanguageText.Add("CMD_RETURN_USAGE_HP", "Correct usage is: /addhp 1-100");
				LanguageText.Add("CMD_RETURN_USAGE_XP_ENERGY", "Correct usage is: /addenergy 1-100");
				LanguageText.Add("CMD_RETURN_USAGE_KARMA", "Correct usage is: /addkarma 1-100");
				LanguageText.Add("CMD_RETURN_USAGE_XP", "Correct usage is: /addxp 1-100");
				//Cmd-Returns-Error
				LanguageText.Add("CMD_ERROR_HP", "SOMETHIN WENT REAL WRONG HERE!");
				LanguageText.Add("CMD_ERROR_ENERGY", "SOMETHIN WENT REAL WRONG HERE!");
				LanguageText.Add("CMD_ERROR_KARMA", "SOMETHIN WENT REAL WRONG HERE!");
				LanguageText.Add("CMD_ERROR_XP", "SOMETHIN WENT REAL WRONG HERE!");
				break;
		}
		LanguageText.Add("CANT_START_SINGLEPLAYER", "Error: Couldn't create singleplayer process.");
		LanguageText.Add("HELP_SAVEITEMS", "Save Loot");
		LanguageText.Add("HELP_SAVEITEMS_TEXT", "Save Loot\n\nUse your shovel to bury and\nsave your items in the ground.\n\nMake sure you stand on the\nexact same spot to retreive\nyour treasure again later.");
		LanguageText.Add("HELP_KARMA", "Karma");
		LanguageText.Add("HELP_KARMA_TEXT", "Karma\n\nIf you attack other players\nyour karma will decline and\nyour name gets red.\n\nKarma improves over time if\nyou don't hurt other players.\n\nPlayers with golden names are\nimmune to damage from other\nplayers (except cars) because of\ntheir 100% karma.");
		LanguageText.Add("TUTORIAL_MESSAGE_7", "Hint: Put a building item in your hand slot to build it.");
		LanguageText.Add("TUTORIAL_MESSAGE_8", "Hint: Right click on another player to open his profile.");
		LanguageText.Add("TUTORIAL_MESSAGE_9", "Hint: Attack with your shovel to bury your items in the ground.");
		LanguageText.Add("TUTORIAL_MESSAGE_10", "Hint: Hold Right Mouse to rotate. Press Space to build.");
		LanguageText.Add("TOOLTIP_RESOURCE", "Attack to loot");
		LanguageText.Add("TOOLTIP_ITEMSTORAGE", "Press E to open");
		LanguageText.Add("TOOLTIP_INTERACT", "Press E to interact");
		LanguageText.Add("TUTORIAL_ISLAND_PICKUPSTICK", "See the stick? Pick it up with E.");
		LanguageText.Add("TUTORIAL_ISLAND_OPENINVENTORY", "Open your inventory with TAB or with the symbol on the left.");
		LanguageText.Add("TUTORIAL_ISLAND_CLICKTARGET", "Click on an animal or hold Space to attack it.");
		LanguageText.Add("TUTORIAL_ISLAND_TARGETRING", "The red ring around your target indicates your target's health.");
		LanguageText.Add("TUTORIAL_ISLAND_CRAFTING", "Press C to open the crafting menu.");
		LanguageText.Add("TUTORIAL_ISLAND_CRAFTCAMPFIRE", "Craft a campfire and drag it into your hand slot in your inventory.");
		LanguageText.Add("TUTORIAL_HINT_BUILDING", "Put a building into your\nhand slot to build it.");
		LanguageText.Add("TUTORIAL_ISLAND_BUILD", "Press Space to build the blue draft hologram. Rotate it with Right Mouse.");
		LanguageText.Add("TUTORIAL_ISLAND_IGNITEFIRECOOK", "Ignite the fire with E and drop your raw items next to it to cook them.");
		LanguageText.Add("TUTORIAL_ISLAND_GETONBOAT", "Ahoi captain! Get on the boat if you are ready.");
		LanguageText.Add("TUTORIAL_ISLAND_FOLLOWSIGNS", "Follow the signs to receive a mission.");
		LanguageText.Add("TUTORIAL_ISLAND_HARVEST", "Attack a tree to collect wood.");
		LanguageText.Add("TUTORIAL_ISLAND_MAP", "Press M to open the map.");
		LanguageText.Add("TUTORIAL_ISLAND_CHAT", "Press T or Enter to chat globally or locally.");
		LanguageText.Add("EVENT_4", "No Fish Around");
		LanguageText.Add("EVENT_5", "Too Many Active Missions");
		LanguageText.Add("EVENT_7", "Already On This Mission");
		LanguageText.Add("EVENT_8", "Out Of Ammo");
		LanguageText.Add("EVENT_9", "Exit Blocked");
		LanguageText.Add("EVENT_10", "Can't Hurt Saints");
		LanguageText.Add("EVENT_11", "Building Repaired");
		LanguageText.Add("STEAM_INV_GET_KEY", "Get 1 Key");
		LanguageText.Add("STEAM_INV_GET_KEYS", "Get 5 Keys");
		LanguageText.Add("STEAM_INV_COMMUNITY_MARKET", "Open\nCommunity\nMarket");
		LanguageText.Add("STEAM_INV_SELL", "Sell");
		LanguageText.Add("STEAM_INV_OPEN_CASE", "Open Case");
		LanguageText.Add("STEAM_INV_EQUIP", "Equip");
		LanguageText.Add("STEAM_INV_UNEQUIP", "Unequip");
		LanguageText.Add("STEAM_INV_UNLOCKING_CASE", "Unlocking Case ...");
		LanguageText.Add("STEAM_INV_NEW_ITEM", "Your New Item:");
		LanguageText.Add("STEAM_PLEASE_REVIEW", "Please leave a nice\nreview if you enjoy\nImmune. Helps us\na lot. Thanks!\n\n<color=\"#87a9b0\">Write Review</color>");
		LanguageText.Add("STEAM_OPEN_CASE", "Open a case to get\na random Steam\nInventory cosmetic\nitem (hat or skin).");
		LanguageText.Add("STEAM_BLUE_ICON", "Follow the blue hat\nicons to get to your\nSteam Inventory.");
		LanguageText.Add("ANTI_SPAM_CHAT", "<color=\"#ff0000\">Please do not spam the chat. Chat disabled for some time.</color>");
		LanguageText.Add("SHOP", "Shop");
		LanguageText.Add("ITEMSHOP_DESC", "Click on an item to buy or sell it.\nPrices may vary in every shop.");
		LanguageText.Add("ITEMSHOP_TOO_LESS_GOLD", "Not enough\nGold Nuggets.\nYou need:");
		LanguageText.Add("REPAIR_NPC_NO_NEED", "This item doesn't\nneed to be repaired.");
		LanguageText.Add("REPAIR_NPC_HOWTO", "Put the item you\nwant to repair\nin your hand.");
		LanguageText.Add("DROP_ITEM_HOWTO", "Drag an item here to\ndrop it on the ground.");
		LanguageText.Add("PLAYERS_ONLINE_DESC", "Left click: open Steam profile / Right click: <color=\"#bb6666\">mute</color>/unmute");
		LanguageText.Add("PLAYERS_INVITE_DESC", "Click on the player you want to invite to your party.");
		LanguageText.Add("NPC_TALK_KEEPMOVING", "Keep moving.");
		LanguageText.Add("NPC_TALK_PHARMACY", "I got pills I gotta take.");
		LanguageText.Add("NPC_TALK_SHOP_FOOD", "Hungry? Come here!");
		LanguageText.Add("NPC_TALK_SHOP_AMMO", "Going on a hunt? I can help.");
		LanguageText.Add("NPC_TALK_MISSION", "I got a small job for you.");
		LanguageText.Add("NPC_TALK_REPAIR", "Want me to repair your items?");
		LanguageText.Add("NPC_TALK_SHOP", "Buying and selling anything! Best prices!");
		LanguageText.Add("NPC_TALK_SHOP_RESOURCES", "Need some wood? Stone? Metal? Or maybe cloth?");
		LanguageText.Add("PARTY_INVITE", "Invite");
		LanguageText.Add("PARTY_KICK", "Kick");
		LanguageText.Add("PARTY_PROMOTE", "Pro-/Demote");
		LanguageText.Add("PARTY", "Party");
		LanguageText.Add("PARTY_SENT_INVITE", "Player has been invited!");
		LanguageText.Add("PARTY_POPUP_INVITED", "\nhas invited you\nto his/her party.");
		LanguageText.Add("PARTY_POPUP_ALREADY_IN_PARTY", "\nis already in\na party.");
		LanguageText.Add("PARTY_POPUP_PRODEMOTED", "\nhas changed your\nparty rank.");
		LanguageText.Add("PARTY_POPUP_KICKED", "\nhas kicked you\nfrom the party.");
		LanguageText.Add("PARTY_POPUP_FULL", "The party is\nalready full.");
		LanguageText.Add("PARTY_DESCRIPTION", "Invite a player to start a party.\n\nParty members are able to use doors\nand tesla coils from each other.");
		LanguageText.Add("MISSION", "Mission");
		LanguageText.Add("LOCATION", "Location");
		LanguageText.Add("REWARD", "Reward");
		LanguageText.Add("TIME_LEFT", "Time Left");
		LanguageText.Add("MISSION_TYPE_1", "Destroy");
		LanguageText.Add("MISSION_TYPE_2", "Kill");
		LanguageText.Add("MISSION_TYPE_3", "Rescue");
		LanguageText.Add("MISSION_PERSON_1", "the Mole");
		LanguageText.Add("MISSION_PERSON_2", "the Major");
		LanguageText.Add("MISSION_PERSON_3", "the Captain");
		LanguageText.Add("MISSION_PERSON_4", "the Soldier");
		LanguageText.Add("MISSION_PERSON_5", "the Thief");
		LanguageText.Add("MISSION_PERSON_6", "the Hostage");
		LanguageText.Add("MISSION_PERSON_7", "the Spy");
		LanguageText.Add("MISSION_PERSON_8", "the Agent");
		LanguageText.Add("MISSION_OBJECT_1", "the Fuel Reservoir");
		LanguageText.Add("MISSION_OBJECT_2", "the Power Generator");
		LanguageText.Add("MISSION_OBJECT_3", "the Communications");
		LanguageText.Add("MISSION_OBJECT_4", "the Supplies");
		LanguageText.Add("FISTS", "Fists");
		LanguageText.Add("BERRIES", "Berries");
		LanguageText.Add("BERRIES_DESC", "Just some ordinary berries. \nCan be used as seed.");
		LanguageText.Add("POTATOES_RAW", "Raw Potato");
		LanguageText.Add("POTATOES_RAW_DESC", "Throw into campfire for \nmaximum tastiness. \nCan be used as seed.");
		LanguageText.Add("POTATOES_COOKED", "Cooked Potato");
		LanguageText.Add("POTATOES_COOKED_DESC", "Best served with a cool beer.");
		LanguageText.Add("MEAT_RAW", "Raw Meat");
		LanguageText.Add("MEAT_RAW_DESC", "Smells funny. Better throw it in \na campfire before eating it.");
		LanguageText.Add("MEAT_COOKED", "Cooked Meat");
		LanguageText.Add("MEAT_COOKED_DESC", "I love vegetarians. \nThey taste awesome.");
		LanguageText.Add("EGGS_RAW", "Raw Egg");
		LanguageText.Add("EGGS_RAW_DESC", "Better throw it in a \ncampfire before eating it.");
		LanguageText.Add("EGGS_COOKED", "Cooked Egg");
		LanguageText.Add("EGGS_COOKED_DESC", "Sunny side up.");
		LanguageText.Add("FISH_RAW", "Raw Fish");
		LanguageText.Add("FISH_RAW_DESC", "Better throw it in a \ncampfire before eating it.");
		LanguageText.Add("FISH_COOKED", "Cooked Fish");
		LanguageText.Add("FISH_COOKED_DESC", "You found Nemo.");
		LanguageText.Add("ENERGY_BAR", "Candy Bar");
		LanguageText.Add("ENERGY_BAR_DESC", "Because you have bigger \nproblems than toothache.");
		LanguageText.Add("MUSHROOMS", "Mushroom");
		LanguageText.Add("MUSHROOMS_DESC", "Paints the apocalypse in \nthe brightest colors.");
		LanguageText.Add("RUMBOTTLE", "Bottle of Rum");
		LanguageText.Add("RUMBOTTLE_DESC", "Alcohol, the cause and \nthe solution to all \nof life's problems");
		LanguageText.Add("CANNED_FOOD", "Canned Food");
		LanguageText.Add("CANNED_FOOD_DESC", "Tastes like old newspaper, \nbut it's better than nothing.");
		LanguageText.Add("WATER_DIRTY", "Dirty Water");
		LanguageText.Add("WATER_DIRTY_DESC", "Cook it on your fireplace \nto make it drinkable.");
		LanguageText.Add("WATER", "Water");
		LanguageText.Add("WATER_DESC", "It's like beer \nbut without taste.");
		LanguageText.Add("BEER", "Beer");
		LanguageText.Add("BEER_DESC", "So much more than \njust a breakfast drink.");
		LanguageText.Add("SODA", "Soda");
		LanguageText.Add("SODA_DESC", "This sugarbomb is \na real lifesaver.");
		LanguageText.Add("WINE", "Wine");
		LanguageText.Add("WINE_DESC", "You can't buy happiness.\nBut you can buy wine.");
		LanguageText.Add("C_WOODENDOOR", "Wooden Door");
		LanguageText.Add("C_WOODENDOOR_DESC", "Only you have the keys \nto open this door.");
		LanguageText.Add("C_METALDOOR", "Metal Door");
		LanguageText.Add("C_METALDOOR_DESC", "Only you have the keys \nto open this door.");
		LanguageText.Add("C_WOODWALL", "Wooden Fence");
		LanguageText.Add("C_WOODWALL_DESC", "Keeps the peace inside \nand the pain outside.");
		LanguageText.Add("C_STONEWALL", "Stone Wall");
		LanguageText.Add("C_STONEWALL_DESC", "Keeps the peace inside \nand the pain outside.");
		LanguageText.Add("C_METALWALL", "Metal Wall");
		LanguageText.Add("C_METALWALL_DESC", "Keeps the peace inside \nand the pain outside.");
		LanguageText.Add("C_WOODWALLWINDOW", "Windowed Fence");
		LanguageText.Add("C_WOODWALLWINDOW_DESC", "Keeps the peace inside \nand the pain outside.");
		LanguageText.Add("C_CAMPFIRE", "Campfire");
		LanguageText.Add("C_CAMPFIRE_DESC", "This will make your raw \nfood edible and tasty if lit.");
		LanguageText.Add("C_WOODCLUB", "Wooden Club");
		LanguageText.Add("C_WOODCLUB_DESC", "A real opinion former.");
		LanguageText.Add("C_FISHINGROD", "Fishing Rod");
		LanguageText.Add("C_FISHINGROD_DESC", "Attack the sea\nto catch fish.");
		LanguageText.Add("C_BED", "Bed");
		LanguageText.Add("C_BED_DESC", "You'll respawn on your \nbed if you die far\nenough away from it.");
		LanguageText.Add("C_LOOTBOX", "Loot Box");
		LanguageText.Add("C_LOOTBOX_DESC", "Build this anywhere\nto store your items.");
		LanguageText.Add("C_TESLACOIL", "Tesla Coil");
		LanguageText.Add("C_TESLACOIL_DESC", "Turns raiders into toast.\nDoesn't attack owner.");
		LanguageText.Add("TNT", "Explosives");
		LanguageText.Add("TNT_DESC", "Put into hand slot\nto plant. Then run.");
		LanguageText.Add("45", ".45 Ammo");
		LanguageText.Add("45_DESC", string.Empty);
		LanguageText.Add("9", "9 mm Ammo");
		LanguageText.Add("9_DESC", string.Empty);
		LanguageText.Add("556", ".556 Ammo");
		LanguageText.Add("556_DESC", string.Empty);
		LanguageText.Add("762", "7.62 mm Ammo");
		LanguageText.Add("762_DESC", string.Empty);
		LanguageText.Add("SHELL", "12 Gauge Ammo");
		LanguageText.Add("SHELL_DESC", string.Empty);
		LanguageText.Add("C_ARROW", "Arrow Ammo");
		LanguageText.Add("C_ARROW_DESC", string.Empty);
		LanguageText.Add("C_STONE", "Stone Ammo");
		LanguageText.Add("C_STONE_DESC", string.Empty);
		LanguageText.Add("PISTOL", "Desert Cuckoo");
		LanguageText.Add("PISTOL_DESC", "Why is there an\neagle engraved?");
		LanguageText.Add("REVOLVER", "Revolver");
		LanguageText.Add("REVOLVER_DESC", "Rick would love\nthis gun.");
		LanguageText.Add("SMG", "SMG");
		LanguageText.Add("SMG_DESC", "Pew pew pew");
		LanguageText.Add("SHOTGUN", "Shotgun");
		LanguageText.Add("SHOTGUN_DESC", "Big bang redefined");
		LanguageText.Add("SNIPERRIFLE", "Sniper Rifle");
		LanguageText.Add("SNIPERRIFLE_DESC", "This belongs\ninto a museum.");
		LanguageText.Add("AK47", "Kulushnikiv");
		LanguageText.Add("AK47_DESC", "Looks like a\nbad replica.");
		LanguageText.Add("C_RIFLE", "Shabby Rifle");
		LanguageText.Add("C_RIFLE_DESC", string.Empty);
		LanguageText.Add("C_REVOLVER", "Shabby Revolver");
		LanguageText.Add("C_REVOLVER_DESC", string.Empty);
		LanguageText.Add("C_SHOTGUN", "Pipe Shotgun");
		LanguageText.Add("C_SHOTGUN_DESC", "Slow fire rate, low\nrange but powerful.");
		LanguageText.Add("C_SLINGSHOT", "Slingshot");
		LanguageText.Add("C_SLINGSHOT_DESC", "First choice for\nevery 13 y/o.");
		LanguageText.Add("C_BOW", "Bow");
		LanguageText.Add("C_BOW_DESC", "Robin Hood would\nbe proud.");
		LanguageText.Add("FIREAXE", "Fire Axe");
		LanguageText.Add("FIREAXE_DESC", "Not actually \nmade of fire");
		LanguageText.Add("MACHETE", "Machete");
		LanguageText.Add("MACHETE_DESC", string.Empty);
		LanguageText.Add("KNIFE", "Knife");
		LanguageText.Add("KNIFE_DESC", "Have a knife day!");
		LanguageText.Add("HAMMER", "Hammer");
		LanguageText.Add("HAMMER_DESC", "Use this to repair\nbuildings or vehicles.");
		LanguageText.Add("PLUNGER", "Plunger");
		LanguageText.Add("PLUNGER_DESC", "The weapon of \na real king.");
		LanguageText.Add("KATANA", "Katana");
		LanguageText.Add("KATANA_DESC", "No pen is mightier \nthan this sword.");
		LanguageText.Add("GIANTSWORD", "Giant Sword");
		LanguageText.Add("GIANTSWORD_DESC", "This thing is\njust ridiculous.");
		LanguageText.Add("MUTANT_CLAW", "Mutant Arm");
		LanguageText.Add("MUTANT_CLAW_DESC", "Just lending a \nhelping hand.");
		LanguageText.Add("UZI", "Gangsta Gun");
		LanguageText.Add("UZI_DESC", "Hold in side grip for\nmaximum coolness.");
		LanguageText.Add("AUTOSHOTGUN", "Auto Shotgun");
		LanguageText.Add("AUTOSHOTGUN_DESC", "Wreaking havoc \nsince 1951");
		LanguageText.Add("TOMMYGUN", "Ancient Gun");
		LanguageText.Add("TOMMYGUN_DESC", "Grandpa's favorite");
		LanguageText.Add("CROWBAR", "Crowbar");
		LanguageText.Add("CROWBAR_DESC", "It says \"Property of Gordon\"");
		LanguageText.Add("WRENCH", "Wrench");
		LanguageText.Add("WRENCH_DESC", "Good for repairing\nloose screws.");
		LanguageText.Add("CLEAVER", "Cleaver");
		LanguageText.Add("CLEAVER_DESC", "Don't mess\nwith the chef!");
		LanguageText.Add("C_SPADE", "Shovel");
		LanguageText.Add("C_SPADE_DESC", "Dig holes to (un)hide \nitems with this!");
		LanguageText.Add("C_STONEHATCHET", "Stone Hatchet");
		LanguageText.Add("C_STONEHATCHET_DESC", "Made of stones\nand stick.");
		LanguageText.Add("C_KNIFE", "Scrap Knife");
		LanguageText.Add("C_KNIFE_DESC", "First choice in\nany prison break.");
		LanguageText.Add("C_TORCH", "Torch");
		LanguageText.Add("C_TORCH_DESC", "Look like the\ncave man you are.");
		LanguageText.Add("C_MACHETE", "Scrap Machete");
		LanguageText.Add("C_MACHETE_DESC", "I hope you got\nyour tetanus shot.");
		LanguageText.Add("BACKPACK", "Backpack");
		LanguageText.Add("BACKPACK_DESC", string.Empty);
		LanguageText.Add("CLOTHBOX", "Airdrop");
		LanguageText.Add("CLOTHBOX_DESC", string.Empty);
		LanguageText.Add("WOOD", "Wood");
		LanguageText.Add("WOOD_DESC", "Can be used as \ncrafting material.");
		LanguageText.Add("METAL", "Metal");
		LanguageText.Add("METAL_DESC", "Can be used as \ncrafting material.");
		LanguageText.Add("STONE", "Stone");
		LanguageText.Add("STONE_DESC", "Can be used as \ncrafting material.");
		LanguageText.Add("CLOTH", "Cloth");
		LanguageText.Add("CLOTH_DESC", "Can be used as \ncrafting material.");
		LanguageText.Add("C_BANDAGES", "Bandages");
		LanguageText.Add("C_BANDAGES_DESC", "Consume this to \nstop a bleeding.");
		LanguageText.Add("ANTIBIOTICS", "Antibiotics");
		LanguageText.Add("ANTIBIOTICS_DESC", "Consume this to \nstop an infection.");
		LanguageText.Add("PAINKILLERS", "Painkillers");
		LanguageText.Add("PAINKILLERS_DESC", "Consume this to \nstop pain.");
		LanguageText.Add("MEDPACK", "Medi Pack");
		LanguageText.Add("MEDPACK_DESC", "Consume this to regain\nhealth. Also stops\nbleeding and pain.");
		LanguageText.Add("KEVLARVEST", "Ballistic Vest");
		LanguageText.Add("KEVLARVEST_DESC", "Hightech armor to \nprotect your body.");
		LanguageText.Add("C_SCRAPVEST", "Wood Armor");
		LanguageText.Add("C_SCRAPVEST_DESC", "Crafted armor to \nprotect your body.");
		LanguageText.Add("C_METALVEST", "Metal Armor");
		LanguageText.Add("C_METALVEST_DESC", "Crafted armor to \nprotect your body.");
		LanguageText.Add("C_LEATHERVEST", "Leather Armor");
		LanguageText.Add("C_LEATHERVEST_DESC", "Crafted armor to \nprotect your body.");
		LanguageText.Add("GUARDIANVEST", "Guardian Vest");
		LanguageText.Add("GUARDIANVEST_DESC", "Hightech armor to \nprotect your body.");
		LanguageText.Add("SNEAKERS", "Sneakers");
		LanguageText.Add("SNEAKERS_DESC", "Make you run faster \nthan the wind.");
		LanguageText.Add("C_SHOES", "Rag Shoes");
		LanguageText.Add("C_SHOES_DESC", "Increase your \nrunning speed.");
		LanguageText.Add("ARMYCAP", "Army Cap");
		LanguageText.Add("ARMYCAP_DESC", string.Empty);
		LanguageText.Add("WOOLCAP", "Wool Hat");
		LanguageText.Add("WOOLCAP_DESC", string.Empty);
		LanguageText.Add("PIRATECAP", "Pirate Cap");
		LanguageText.Add("PIRATECAP_DESC", string.Empty);
		LanguageText.Add("BUNNYEARS", "Bunnyears");
		LanguageText.Add("BUNNYEARS_DESC", "These make you \nfeel as if you \nrun faster");
		LanguageText.Add("BASEBALLCAP", "Baseball Cap");
		LanguageText.Add("BASEBALLCAP_DESC", string.Empty);
		LanguageText.Add("SANTAHAT", "Santa's Hat");
		LanguageText.Add("SANTAHAT_DESC", "Ho ho hold \nyour hands up!");
		LanguageText.Add("COWBOYHAT", "Cowboy Hat");
		LanguageText.Add("COWBOYHAT_DESC", "Howdy partner!");
		LanguageText.Add("RUSSIACAP", "Flappy Ears Hat");
		LanguageText.Add("RUSSIACAP_DESC", string.Empty);
		LanguageText.Add("TOPHAT", "Top Hat");
		LanguageText.Add("TOPHAT_DESC", "You sir, look awesome!");
		LanguageText.Add("BEANIECAP", "Beanie Cap");
		LanguageText.Add("BEANIECAP_DESC", string.Empty);
		LanguageText.Add("ROADCONE", "Road Cone");
		LanguageText.Add("ROADCONE_DESC", "This would make \nan exquisite hat.");
		LanguageText.Add("BUCKET", "Bucket Helmet");
		LanguageText.Add("BUCKET_DESC", "You are the \nscrap knight.");
		LanguageText.Add("BIKERHELMET", "Biker Helmet");
		LanguageText.Add("BIKERHELMET_DESC", "Dude, where's \nmy bike?");
		LanguageText.Add("HORSEHEAD", "Horse Mask");
		LanguageText.Add("HORSEHEAD_DESC", string.Empty);
		LanguageText.Add("GOLD", "Gold Nuggets");
		LanguageText.Add("GOLD_DESC", "The only currency left \nwhen sh*t hits the fan.");
		LanguageText.Add("CONDITION_FREEZING", "Freezing\n\nBuild a campfire or\nput on some clothes.\n\nREDUCES ENERGY");
		LanguageText.Add("CONDITION_BLEEDING", "Bleeding\n\nCraft some bandages\nand consume them.\n\nREDUCES HEALTH");
		LanguageText.Add("CONDITION_RADIATION", "Radiation\n\nGet out of the\nradiation area.\nREDUCES HEALTH\nREDUCES ENERGY");
		LanguageText.Add("CONDITION_INFECTION", "Infection\n\nFind some antibiotics\nto heal the infection.\n\nREDUCES HEALTH");
		LanguageText.Add("CONDITION_STARVATION", "Starvation\n\nFind some food to\nfill your belly.\n\nREDUCES HEALTH");
		LanguageText.Add("CONDITION_PAIN", "Pain\n\nFind painkillers to\ncure the pain.\n\nREDUCES SPEED");
		LanguageText.Add("PLAYERCOUNT", "Survivors Online");
		LanguageText.Add("CURRENCY", "Gold");
		LanguageText.Add("BUY", "Buy");
		LanguageText.Add("SELL", "Sell");
		LanguageText.Add("REPAIR", "Repair");
		LanguageText.Add("MAP_NAMES", "A: Hometown\nB: Gastown\nC: Terminus\nD: Venore\nE: Fort Benning\nF: Garbage Station\nG: Tallahassee\nH: Riverside\nI: Gas Ranch\nJ: Power Plant\nK: Alexandria\nL: Area 42\nM: Madison\nN: Valley\nO: Prison");
		LanguageText.Add("MISSION_LOCATION_1", "Hometown");
		LanguageText.Add("MISSION_LOCATION_2", "Gastown");
		LanguageText.Add("MISSION_LOCATION_3", "Terminus");
		LanguageText.Add("MISSION_LOCATION_4", "Venore");
		LanguageText.Add("MISSION_LOCATION_5", "Fort Benning");
		LanguageText.Add("MISSION_LOCATION_6", "Garbage Station");
		LanguageText.Add("MISSION_LOCATION_7", "Tallahassee");
		LanguageText.Add("MISSION_LOCATION_8", "Riverside");
		LanguageText.Add("MISSION_LOCATION_9", "Gas Ranch");
		LanguageText.Add("MISSION_LOCATION_10", "Power Plant");
		LanguageText.Add("MISSION_LOCATION_11", "Airport");
		LanguageText.Add("MISSION_LOCATION_12", "Alexandria");
		LanguageText.Add("MISSION_LOCATION_13", "Area 42");
		LanguageText.Add("MISSION_LOCATION_14", "Valley");
		LanguageText.Add("MISSION_LOCATION_15", "Prison");
		LanguageText.Add("MENU_CREDITS", "Game By: Gabriel Morgenstern, Art By: Alex Lusth, Niklas Hallin, Evgeny Lyapin, Adriano de Regino, Thomas Grünberg\nSpecial Thanks: Christine N., Alex H., Jörn J., Maki L., Andrea S. and all alpha/beta testers!");
	}
}
